# Generated by Django 4.2.6 on 2023-10-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='username',
        ),
    ]
