# Generated by Django 4.2.6 on 2023-10-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_staff_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='staff',
        ),
    ]
